### ISSUE TITLE
Date Shot in Photoview is 1 or 2 hours ahead of EXIF timestamp

### ISSUE THREAD

**Issue by bluecasita** [photoview/photoview#1298]
In Photoview in all cases the timestamp being shown in the "Date Shot" field on the photo information is one or two hours ahead (+1 or +2) of the actual EXIF timestamp.  For example, a photo taken at 18:31 would show a "Date Shot" of 19:31 or 20:31.  I have no idea why this is happening, and it is none consistent - at first I thought about DST, but the +1 or +2 hours are not consistently at the same times of year.  Also all phones are impacted, including those taken overseas, or those taken in my local timezone (same as the server).

Any idea what could be happening here?

Example 1:
exiftool -time:all -G IMG_20240810_191616_00.jpg
[File]          File Modification Date/Time     : 2025:08:17 11:23:15-05:00
[File]          File Access Date/Time           : 2025:08:18 23:22:43-05:00
[File]          File Inode Change Date/Time     : 2025:08:19 10:09:18-05:00
[EXIF]          Modify Date                     : 2024:08:10 19:16:16
[EXIF]          Date/Time Original              : 2024:08:10 19:16:16
[EXIF]          Create Date                     : 2024:08:10 19:16:16
[EXIF]          Offset Time                     : -05:00
[EXIF]          Offset Time Original            : -05:00
[EXIF]          Offset Time Digitized           : -05:00
[EXIF]          Sub Sec Time                    : 245
[EXIF]          Sub Sec Time Original           : 245
[EXIF]          Sub Sec Time Digitized          : 245
[EXIF]          GPS Time Stamp                  : 00:16:12
[EXIF]          GPS Date Stamp                  : 2024:08:11
[ICC_Profile]   Profile Date Time               : 2023:03:09 10:57:00
[Composite]     Create Date                     : 2024:08:10 19:16:16.245-05:00
[Composite]     Date/Time Original              : 2024:08:10 19:16:16.245-05:00
[Composite]     Modify Date                     : 2024:08:10 19:16:16.245-05:00
[Composite]     GPS Date/Time                   : 2024:08:11 00:16:12Z

This shows "Date Shot" in Photoview at 21:16 (9:16PM)

Example 2:
exiftool -time:all -G IMG_20241125_193442_00.jpg
[File]          File Modification Date/Time     : 2025:08:17 11:43:43-05:00
[File]          File Access Date/Time           : 2025:08:18 23:26:29-05:00
[File]          File Inode Change Date/Time     : 2025:08:19 10:09:18-05:00
[EXIF]          Modify Date                     : 2024:11:25 19:34:42
[EXIF]          Date/Time Original              : 2024:11:25 19:34:42
[EXIF]          Create Date                     : 2024:11:25 19:34:42
[EXIF]          Offset Time                     : +00:00
[EXIF]          Offset Time Original            : +00:00
[EXIF]          Offset Time Digitized           : +00:00
[EXIF]          Sub Sec Time                    : 221
[EXIF]          Sub Sec Time Original           : 221
[EXIF]          Sub Sec Time Digitized          : 221
[EXIF]          GPS Time Stamp                  : 19:13:57
[EXIF]          GPS Date Stamp                  : 2024:11:25
[ICC_Profile]   Profile Date Time               : 2023:03:09 10:57:00
[Composite]     Create Date                     : 2024:11:25 19:34:42.221+00:00
[Composite]     Date/Time Original              : 2024:11:25 19:34:42.221+00:00
[Composite]     Modify Date                     : 2024:11:25 19:34:42.221+00:00
[Composite]     GPS Date/Time                   : 2024:11:25 19:13:57Z

This shows Date Shot in Photoview at 20:34 (8:34PM)

**Comment by kkovaletp** [comment]
@Matt-UKTX, thanks for reporting. It looks like we parse timezone from the exiftool results inconsistently...

@googollee, we discussed this case recently in #1297. Please take a look.

**Comment by googollee** [comment]
I don't think it relates to #1297 since it doesn't merge yet.

@Matt-UKTX is it possible to provide a test file here and give us the right shot date? Thanks.

**Comment by googollee** [comment]
Currently, we use EXIF data first if it exists, because it's the time recorded by the camera.
In your example, `IMG_20240810_191616_00.jpg` has EXIF data:

```
[EXIF] Modify Date : 2024:08:10 19:16:16
[EXIF] Date/Time Original : 2024:08:10 19:16:16
[EXIF] Create Date : 2024:08:10 19:16:16
```

So `photoview` loads it as `2024:08:10 19:16:16`.

`IMG_20241125_193442_00.jpg` has EXIF data:

```
[EXIF] Modify Date : 2024:11:25 19:34:42
[EXIF] Date/Time Original : 2024:11:25 19:34:42
[EXIF] Create Date : 2024:11:25 19:34:42
```

So `photoview` loads it as `2024:11:25 19:34:42`.

The problem is, EXIF stores timezone in another field, like:

```
[EXIF] Offset Time : -05:00
[EXIF] Offset Time Original : -05:00
[EXIF] Offset Time Digitized : -05:00
```

Which `photoview` doesn't use. It's the problem. I'll see how to fix it.

**Comment by googollee** [comment]
@Matt-UKTX may I know which camera are you using? Can it set a time zone on the camera, but not thought syncing with a phone?

@kkovaletp can you check if your camera file has a time zone exif info?

My 10y+ old camrea doesn't provide that info.

**Comment by kkovaletp** [comment]
> can you check if your camera file has a time zone exif info?

Actually, you can use the CR3 test image from our another open case:

```bash
exiftool -time:all -s ./test/Canon250D_cRAW-16_9.CR3
FileModifyDate                  : 2025:08:30 13:28:47+03:00
FileAccessDate                  : 2025:08:30 13:30:16+03:00
FileInodeChangeDate             : 2025:08:30 13:30:14+03:00
DateTimeOriginal                : 2019:09:13 14:36:48
OffsetTime                      : +02:00
OffsetTimeOriginal              : +02:00
OffsetTimeDigitized             : +02:00
SubSecTime                      : 87
SubSecTimeOriginal              : 87
SubSecTimeDigitized             : 87
TimeZone                        : +02:00
TimeZoneCity                    : Cairo
DaylightSavings                 : Off
CreateDate                      : 2019:09:13 15:36:48+03:00
ModifyDate                      : 2019:09:13 15:36:48+03:00
TrackCreateDate                 : 2019:09:13 15:36:48+03:00
TrackModifyDate                 : 2019:09:13 15:36:48+03:00
MediaCreateDate                 : 2019:09:13 15:36:48+03:00
MediaModifyDate                 : 2019:09:13 15:36:48+03:00
TimeStamp                       : 2019:09:13 14:36:48.87
SubSecCreateDate                : 2019:09:13 14:36:48.87+02:00
SubSecDateTimeOriginal          : 2019:09:13 14:36:48.87+02:00
SubSecModifyDate                : 2019:09:13 14:36:48.87+02:00
```

**Comment by googollee** [comment]
Yes, I know that file has timezone info. I want to see how a camera generates that info, if a camera provides a way to change the timezone on the machine, or a camera only depends on syncing with a phone. What does it generate with EXIF if a camera doesn't sync with a phone, but changes the time on the camera?

**Comment by googollee** [comment]
I'm also thinking about a proper way to get the right timezone:

- If exif provides it, we should use it
- If not, but provides GPS, we may use GPS to get a timezone, like [this library](https://pkg.go.dev/github.com/ringsaturn/tzf)
  - It may not always be correct, and the timezone mapping to a location may change in the future. There are many ongoing territorial disputes.
- At last, use the local timezone.

**Comment by bluecasita** [comment]
I'm happy to provide a file if needed.  In my case, the exif info in the photo itself is completely correct.  What is strange is that the "Date Shot" shown in Photoview is always +1 or +2 hours off from that time.  So for any file, if the exif time is 19:16, Date Shot in Photoview will show 20:16 or 21:16.  I have not established a pattern for why some are +1 and some are +2.  Thought it might be DST related, but this happens at all different times of the year.

I am using a Google Pixel 9 Pro XL, but this happens on iPhones and other cameras too.  It does not appear to be location specific or camera specific.  What we need to determine is how "Date Shot" is generated.  Personally, I don't want all the date time stamps normalized to my "home" location.  I just want to see the date/time when the photo was actually taken in that location/timezone.

**Comment by kkovaletp** [comment]
> Yes, I know that file has timezone info. I want to see how a camera generates that info, if a camera provides a way to change the timezone on the machine, or if a camera only depends on syncing with a phone. What does it generate with EXIF if a camera doesn't sync with a phone, but changes the time on the camera?

I have no physical camera. My family and I use phones only. They fill the time-related fields in EXIF metadata based on the system time. I assume that cameras do the same: they should have internal system clock settings and use the current date-time with the current timezone to fill that EXIF metadata. Sync with a phone or PC would update the time, but the timezone should be autodetected based on the GPS coordinates + the current date (to switch DST on/off). This is my assumption only.

**Comment by kkovaletp** [comment]
> I'm also thinking about a proper way to get the right timezone

I like your steps.
Regarding the timezone changes, I periodically see such updates for my phone, so I guess there should be a package with actual timezones for Linux (not sure if it would be suitable for our GPS to TZ mapping) or a library with this data included and regularly updated. The fallback source might be a webservice on the Internet (like we use Mapbox), but I'd prefer to have this data be offline for users' privacy PoV.

**Comment by kkovaletp** [comment]
> I don't want all the date time stamps normalized to my "home" location. I just want to see the date/time when the photo was actually taken in that location/timezone.

Makes sense. Currently, we show only the date and time on the UI, but we need to show also the timezone in a clear human-readable form, like <TZ_abbr> <±offset> <SDT|DST>
This will make the value clear and consistent.

But for consistent sorting, we still need to be able to normalize those different timezones to the same one. It could be a server's timezone or UTC. My personal preference is to use UTC, because people move sometimes, and the server's timezone is not constant, while we currently don't support metadata updates for already scanned media.

**Comment by bluecasita** [comment]
UTC makes sense.  I would be curious to know the cause of the +1 or +2 hour offset, any clues yet?  This happens in my case no matter what timezone I am in, whether DST is in effect or not.  Why does "Date Shot" get augemented by 1 or 2 hours?

BTW, can I just say how impressed I am with the active development and responsiveness of the Photoview Team?  I had Immich before, and while it had a lot of cool "bells and whistles" there were constant breaking changes and it was overly complex.  Photoview just works.  Great product and great team.

**Comment by googollee** [comment]
> I would be curious to know the cause of the +1 or +2 hour offset, any clues yet?

It's because `photoview` doesn't consider the timezone in EXIF `OffsetTimeOriginal`. There are some historical reasons.

> we still need to be able to normalize those different timezones to the same one.

Actually, I'd like to see the local time and timezone of an image. The local time is clearer to remember when I took the photo, than an UTC time.

**Comment by kkovaletp** [comment]
> Actually, I'd like to see the local time and timezone of an image. The local time is clearer to remember when I took the photo, than an UTC time.

Sorry, maybe I wasn't clear enough:
The DateShot value is used for:
- showing the date and time when the media was originally created (shown on the media sidebar together with other EXIF metadata). This should show the original value, formatted for humans. Something like: <date> <time> <TZ_abbr> <±offset> <SDT|DST> and with no normalization, just formatting of the original value for easy reading. As far as I understand, it is stored in the `media_exif.date_shot` DB field
- sorting the media and showing the dates on the Timeline. This value has to be normalized to UTC (preferred) or local server timezone to consistently and correctly sort media files from different timezones and display them in the correct order on the Timeline. As far as I understand, it is stored in the `media.date_shot` DB field.

Hope that now my PoV is clear for you.

**Comment by bluecasita** [comment]
> > I would be curious to know the cause of the +1 or +2 hour offset, any clues yet?
> 
> It's because `photoview` doesn't consider the timezone in EXIF `OffsetTimeOriginal`. There are some historical reasons.
> 
> > we still need to be able to normalize those different timezones to the same one.
> 
> Actually, I'd like to see the local time and timezone of an image. The local time is clearer to remember when I took the photo, than an UTC time.

Sorry if I am being stupid, but this doesn't make sense to me.  In my case ALL my photos are off by either +1 or +2 regardless of the OffsetTimeOriginal.  Look at these two specific examples:

Example 1:
exiftool -time:all -G IMG_20240810_191616_00.jpg
[File] File Modification Date/Time : 2025:08:17 11:23:15-05:00
[File] File Access Date/Time : 2025:08:18 23:22:43-05:00
[File] File Inode Change Date/Time : 2025:08:19 10:09:18-05:00
[EXIF] Modify Date : 2024:08:10 19:16:16
[EXIF] Date/Time Original : 2024:08:10 19:16:16
[EXIF] Create Date : 2024:08:10 19:16:16
[EXIF] Offset Time : -05:00
[EXIF] Offset Time Original : -05:00
[EXIF] Offset Time Digitized : -05:00
[EXIF] Sub Sec Time : 245
[EXIF] Sub Sec Time Original : 245
[EXIF] Sub Sec Time Digitized : 245
[EXIF] GPS Time Stamp : 00:16:12
[EXIF] GPS Date Stamp : 2024:08:11
[ICC_Profile] Profile Date Time : 2023:03:09 10:57:00
[Composite] Create Date : 2024:08:10 19:16:16.245-05:00
[Composite] Date/Time Original : 2024:08:10 19:16:16.245-05:00
[Composite] Modify Date : 2024:08:10 19:16:16.245-05:00
[Composite] GPS Date/Time : 2024:08:11 00:16:12Z

**Example 1 shows "Date Shot" in Photoview at 21:16 (9:16PM)**

Example 2:
exiftool -time:all -G IMG_20241125_193442_00.jpg
[File] File Modification Date/Time : 2025:08:17 11:43:43-05:00
[File] File Access Date/Time : 2025:08:18 23:26:29-05:00
[File] File Inode Change Date/Time : 2025:08:19 10:09:18-05:00
[EXIF] Modify Date : 2024:11:25 19:34:42
[EXIF] Date/Time Original : 2024:11:25 19:34:42
[EXIF] Create Date : 2024:11:25 19:34:42
[EXIF] Offset Time : +00:00
[EXIF] Offset Time Original : +00:00
[EXIF] Offset Time Digitized : +00:00
[EXIF] Sub Sec Time : 221
[EXIF] Sub Sec Time Original : 221
[EXIF] Sub Sec Time Digitized : 221
[EXIF] GPS Time Stamp : 19:13:57
[EXIF] GPS Date Stamp : 2024:11:25
[ICC_Profile] Profile Date Time : 2023:03:09 10:57:00
[Composite] Create Date : 2024:11:25 19:34:42.221+00:00
[Composite] Date/Time Original : 2024:11:25 19:34:42.221+00:00
[Composite] Modify Date : 2024:11:25 19:34:42.221+00:00
[Composite] GPS Date/Time : 2024:11:25 19:13:57Z

**Example 2 shows Date Shot in Photoview at 20:34 (8:34PM)**

I agree that I'd definitely want to see the time date/time the photo was actually taken in "Date Shot".  I don't care about timezone, but normalizing all of them behind the scenes to UTC (for sorting, etc.) makes perfect sense.

**Comment by kkovaletp** [comment]
> Example 1 shows "Date Shot" in Photoview at 21:16 (9:16PM)
> [EXIF] Date/Time Original : 2024:08:10 19:16:16

Photoview reads the date-time and adds the server's timezone (+01:00). In this case, it was summer, so DST was included, adding 1 more hour.

> Example 2 shows Date Shot in Photoview at 20:34 (8:34PM)
> [EXIF] Date/Time Original : 2024:11:25 19:34:42

In this case, it was late fall, so DST wasn't applied, resulting in +1 hour.

Anyway, the original timezone is ignored. Only the date and time matter. Hope, now it is clear.

**Comment by bluecasita** [comment]
I guess that is what is confusing me. If the server is in Central Time (-6) why would it be off by one hour or two hours? 

If the server is in UTC then it is still confusing as Example 1 was shot in UTC+1 and Example 2 was shot in UTC-5. 

I guess it doesn't really matter as long as it makes sense to you guys and you can fix it 🙂

**Comment by googollee** [comment]
@Matt-UKTX Could you run the server with `ghcr.io/googollee/photoview:exif-timezone-1298` image? If you are using docker compose config, update the line `image: photoview/photoview` to `image: ghcr.io/googollee/photoview:exif-timezone-1298`.

After restarting the server, add those images with wrong time to the repo again (maybe copy to another folder), then rescan the library and check the result.

**Comment by bluecasita** [comment]
So I tried the new image and got an interesting result.

Example 1 now shows Date Shot as 8/11/2024, 3:16:16 AM

Here is the EXIF data:
exiftool -time:all -G IMG_20240810_191616_00.jpg
[File] File Modification Date/Time : 2025:08:17 11:23:15-05:00
[File] File Access Date/Time : 2025:08:18 23:22:43-05:00
[File] File Inode Change Date/Time : 2025:08:19 10:09:18-05:00
[EXIF] Modify Date : 2024:08:10 19:16:16
[EXIF] Date/Time Original : 2024:08:10 19:16:16
[EXIF] Create Date : 2024:08:10 19:16:16
[EXIF] Offset Time : -05:00
[EXIF] Offset Time Original : -05:00
[EXIF] Offset Time Digitized : -05:00
[EXIF] Sub Sec Time : 245
[EXIF] Sub Sec Time Original : 245
[EXIF] Sub Sec Time Digitized : 245
[EXIF] GPS Time Stamp : 00:16:12
[EXIF] GPS Date Stamp : 2024:08:11
[ICC_Profile] Profile Date Time : 2023:03:09 10:57:00
[Composite] Create Date : 2024:08:10 19:16:16.245-05:00
[Composite] Date/Time Original : 2024:08:10 19:16:16.245-05:00
[Composite] Modify Date : 2024:08:10 19:16:16.245-05:00
[Composite] GPS Date/Time : 2024:08:11 00:16:12Z

Example 2 now shows Date Shot as 11/25/2024, 9:34:42 PM

Here is the EXIF data:
exiftool -time:all -G IMG_20241125_193442_00.jpg
[File] File Modification Date/Time : 2025:08:17 11:43:43-05:00
[File] File Access Date/Time : 2025:08:18 23:26:29-05:00
[File] File Inode Change Date/Time : 2025:08:19 10:09:18-05:00
[EXIF] Modify Date : 2024:11:25 19:34:42
[EXIF] Date/Time Original : 2024:11:25 19:34:42
[EXIF] Create Date : 2024:11:25 19:34:42
[EXIF] Offset Time : +00:00
[EXIF] Offset Time Original : +00:00
[EXIF] Offset Time Digitized : +00:00
[EXIF] Sub Sec Time : 221
[EXIF] Sub Sec Time Original : 221
[EXIF] Sub Sec Time Digitized : 221
[EXIF] GPS Time Stamp : 19:13:57
[EXIF] GPS Date Stamp : 2024:11:25
[ICC_Profile] Profile Date Time : 2023:03:09 10:57:00
[Composite] Create Date : 2024:11:25 19:34:42.221+00:00
[Composite] Date/Time Original : 2024:11:25 19:34:42.221+00:00
[Composite] Modify Date : 2024:11:25 19:34:42.221+00:00
[Composite] GPS Date/Time : 2024:11:25 19:13:57Z

**Comment by googollee** [comment]
@Matt-UKTX What's your timezones of the browser and the server?

**Comment by bluecasita** [comment]
> [@Matt-UKTX](https://github.com/Matt-UKTX) What's your timezones of the browser and the server?

I am currently in Greece for vacation, so the timezone of my browser is GMT+3 (on my local laptop).  The timezone of my server should be US Central Time GMT-5.  

If Date Shot is trying to translate into my local browser time, that might make more sense (still seems to be off by an hour), but honestly, I just want to see the value in the EXIF data regardless of timezone, DST, etc. 

Here's what would be ideal:
Date Shot: <Date/Time Original> UTC +/-Offset Time

For example 1:
Date Shot: 2024/08/10 19:16:16 (UTC -05:00)

For example 2:
Date Shot: 2024/11/25 19:34:42 (UTC +00:00)

**Comment by googollee** [comment]
I just realized this. Currently `photoview` transfers date in UTC, which means it lost the original timezone. The web show the time in the local timezone of the browser.

**Comment by bluecasita** [comment]
Can it be fixed?

**Comment by kkovaletp** [comment]
Yes, but with more effort and in 2 steps: 
- 1st API should fix the behavior of storing and reporting these dates consistently.
- Then, UI should fix the way it reads and displays those dates in browsers.

**Comment by bluecasita** [comment]
Great. Let me know if you need me to do more testing. I'm happy to help. The fact that I am in a different time zone than the server will actually be good to covering all scenarios.

**Comment by bluecasita** [comment]
Any update on this fix?

**Comment by kkovaletp** [comment]
@Matt-UKTX, all updates are in the linked PR. Feel free to go there and read the conversation thread

**Comment by bluecasita** [comment]
I looked at the PR and installed the `master` version.  However this still isn't fixed.  It looks like all my pics are now off by 5 hours.

**Comment by kkovaletp** [comment]
@bluecasita, the `master` branch contains only the UI (representation) part of the fix. The processing part is still in the #1300 PR.
