### ISSUE TITLE
Photoview doesn't generate/show thumbnils

### ISSUE THREAD

**Issue by ituri** [photoview/photoview#757]
Using the latest docker-compose file, I set up photoview on my local server. The photos are on a different drive which is mounted via NFS. Also the media cache is supposed to be on the different drive too. It is also mounted via NFS. Here's my `docker-compose.yml`:

```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8202:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/mnt/docker/photoview

      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      - MAPBOX_TOKEN=secret

    volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /mnt/photo:/photos:ro

volumes:
  db_data:
  api_cache:
```

Here is a screenshot of photoview after it was supposed to have generated the thumbnails:
![Screenshot 2022-10-11 at 14 13 33](https://user-images.githubusercontent.com/871297/195086657-6e7cb6d6-c8fe-48af-9ae8-79e85ac4dd2c.png)
The log is full of messages like this:
```
2022/10/11 12:12:39 Queue waiting for lock
2022/10/11 12:12:39 Queue running: in_progress: 2, max_tasks: 3, queue_len: 10
2022/10/11 12:12:39 Queue starting job
2022/10/11 12:12:39 Queue waiting
2022/10/11 12:12:39 Starting job
2022/10/11 12:12:39 Job finished
```

When I enter the docker container, I can also succesfully write to the media cache directory so I don't suppose it's a permission issue. Any ideas on what to do here?

**Comment by Hobbesdcc** [comment]
I am also seeing this exact same behavior, seeing everything as white boxes. Not sure how to fix it. This started a few weeks back. I've tried to remake the container a few times to no avail.

I removed my whole container and the volumes then pointed to a folder with only a few photos in it, that worked fine. Added a few more and scanned again, and that worked, but when I added the rest ~3000 photos, everything broke down. Seems like all the newly added photo exist, but are white boxes, and clicking on them shows nothing, sort of like things broke down after they were scanned but before they were processed. 

Here is my setup incase that helps sort out the issue. I'm running in a docker container on a Synology NAS.

Docker compose:
> version: "3" 
> 
> services: 
>   db: 
>     container_name: Photoview_DB 
>     image: mariadb:10.5 
>     restart: always 
>     environment: 
>       - MYSQL_DATABASE=photoview 
>       - MYSQL_USER=photoview 
>       - MYSQL_PASSWORD=photosecret 
>       - MYSQL_RANDOM_ROOT_PASSWORD=1 
>     volumes: 
>       - db_data:/var/lib/mysql 
>  
>   photoview: 
>     container_name: Photoview 
>     image: viktorstrate/photoview:latest 
>     restart: always 
>     ports: 
>       - "8030:80" 
>     depends_on: 
>       - db 
>  
>     environment: 
>       - PHOTOVIEW_DATABASE_DRIVER=mysql 
>       - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview 
>       - PHOTOVIEW_LISTEN_IP=photoview 
>       - PHOTOVIEW_LISTEN_PORT=80 
>       - PHOTOVIEW_MEDIA_CACHE=/app/cache
>  
>     volumes: 
>       -  db_data:/app/cache 
>       - /volume1/Nas/[Phone] Backup Pull:/PhoneUnsorted:ro
>  
> volumes: 
>   db_data: 
>   api_cache:

**Comment by ituri** [comment]
My photos also reside on a Synology NAS. Could it be that there is some kind of timeout when trying to retrieve the photos? I must admit that my NAS is not the fastest one and that this could be an issue of there is a timeout of any sort.

**Comment by DawidPietrykowski** [comment]
I'm seeing the same issue but only the timeline view is broken, clicking the info button on any image in the timeline shows error: `could not get media by media_id and user_id from database: record not found`
The images are also not loading when clicked so it seems like it's more than just a thumbnail issue. Videos however seem to be just fine, showing correct thumbnail and can be played

**Comment by EgorSmutkin** [comment]
I fixed the grey thumbnails on my side by adding the PHOTOVIEW_DISABLE_VIDEO_ENCODING=1 environment variable and scanning folders again. Of course, this makes all the video disappear, but some of them got back after setting the above variable back to 0 and running another scan. I also noticed the following warning in the logs, that's probably causing the whole thumbnail generation process to fail:
`WARN: ScanVideoMetadata for 20190805_112042.mp4 failed: scan video metadata failed (20190805_112042.mp4): could not read video metadata (20190805_112042.mp4): error running ffprobe [] signal: killed`
Removing the above .mp4 from the server fixed the rest of the missing records. Still not sure why it was failing on that particular file. Guess it would be nice to have a separate page to track any scan errors.

**Comment by banigithub-2** [comment]
I had the same thing.  It led me to point exiftool at the files, and found that some had become corrupted (not Photoview's fault of course).  It causes the scanned to just crash out, and you don't get the thumbnails created.  The other sign is that in your Albums, you don't see all of the pictures that are in your folder: you only see files up to the one that caused the scanner to crash.  It would be lovely if the Photoview scanner could spot that there's a dodgy file, log it, and carry on regardless...

**Comment by DaxtonD** [comment]
Hello everyone!

I'm having the same issue. I finally had the time to dig in and try to see what's causing the problem.

I randomly selected 50 images from my library and imported them into Photoview. I Noticed that the first 30 images had no thumbnail and the rest were all fine.
I started removing images and re-importing the library until I had 3 images.

image 1 - showed a thumbnail
image 2 - no thumbnail
image 3 - no thumbnail

I looked at the actual images and the only thing different was the image size. Image 2 was a wide panoramic from my cell phone. I removed this image from the library and re-imported image 1 and image 3.
This time, they both imported correctly showed a thumbnail.

It would appear as though when Photoprisim is importing images, it has a problem handling the image dimensions in a single photo. This somehow causes it to have a problem with every image it imports afterwards. 

attached is the image that caused the problem for me.
I hope this is enough for the developer to correct it! This is the only thing preventing me from completely switching over to Photoview.
![20180209_082838](https://user-images.githubusercontent.com/96708688/201552802-bf12f794-27e1-4215-adc9-2a59904cfd26.jpg)

**Comment by viktorstrate** [comment]
Does this problem also occur on the `:edge` tag?

**Comment by DaxtonD** [comment]
Library is finished importing.
Sorry to report the problem persists.
It seems like as soon as a problem is encountered with a photo, the importer fails to process every subsequent picture.

**Comment by DaxtonD** [comment]
sloniupl, thanks!
Yes, I can confirm the same thing. Everything is working for me as well with tag 2.3.12
I will say that while Photoview was scanning images, it appeared as though this problem persisted. Thumbnails weren't generated correctly as the scanner was in progress. It wasn't until after the scanner completed that all the thumbnails correctly showed.

**Comment by Dinth** [comment]
> I'm seeing the same issue but only the timeline view is broken, clicking the info button on any image in the timeline shows error: `could not get media by media_id and user_id from database: record not found`
> The images are also not loading when clicked so it seems like it's more than just a thumbnail issue. Videos however seem to be just fine, showing correct thumbnail and can be played

Hey. Have you managed to resolve those errors? Im seeing the same on a new installation and database, except for me videos are also affected. Reverting to 2.3.12 doesnt help

**Comment by spin6lock** [comment]
Photoview Version
Release Version
2.3.12 ([0b9d04ef](https://github.com/photoview/photoview/commit/0b9d04eff2b6f896a70e8d081b6706dc4068f732))
Build date
2022-02-11T12:07:25Z

After switch to photoview:2.3.12 and mount db on new directory, still got same problem. Thumbnails was not showed both in timeline and directory view.

**Comment by spin6lock** [comment]
After watch the Stats in portainer for a while, I found the cause maybe the exiftool. exiftool keep calling up darktable-cli to convert ARW raw file to JPG. And the memory is rising up and hit the limit finally. 

<img width="806" alt="photoview_mem_stat" src="https://user-images.githubusercontent.com/734304/214283703-b3e5ce00-be8a-49c4-9b5a-d82d3f1fd5e8.png">

See the lowest memory point above

**Comment by DaxtonD** [comment]
Hello to all,

I have a photo library of about 10,000 files, all of which have been taken on my various mobile Android phones over the years. They've all been synced with Resilio sync.
I've painstakingly scanned my entire library while watching the log files. Each time an error was thrown, I removed the suspected photo from my library and re-scanned.  
With all of these photos removed from my library, Photoview has now properly scanned and processed all of my images correctly.
Although I have no idea why these photos caused the processing to fail, I've now segregated them and will share a link to where they can be downloaded and analyzed by the developers. Also, there's a text file in the folder with a copy of the log file during an error.
I really hope this helps with the development and progression of this wonderful application.
If I can be of assistance in any way, kindly let me know.


Thanks!
Daxton

Images can be found here: 

https://drive.google.com/drive/folders/1k3Bb-xr0RkPePZCSoLcXgJZBSPvOEHzv?usp=sharing

**Comment by tymmej** [comment]
I had same problem.
It was caused by weird video dimensions (#809).

Another issue is that if processing media fails half through folder it will leave it at that state: some photos will be OK, rest `could not get media by media_id and user_id from database: record not found` and no thumbnail. Subsequent scans ignores files with no thumbnails and album is left in broken state.

Maybe scanner should not quit in case of error (I believe it happens at https://github.com/photoview/photoview/blob/master/api/scanner/scanner_album.go#L106)  and try to process rest of photos in album?

**Comment by helgehatt** [comment]
Ann updates on this issue? The app isn’t usable as long as this bug persists.

Instead of fixing all issues causing the scan to fail, the first step should be to make the processing continue even though some media fails.

**Comment by kkovaletp** [comment]
The main cause for this issue is fixed by #892. The other mentioned here problem should be fixed by updating Darktable to the latest version by the #863, so closing this issue as completed
